### ISSUE TITLE
break="no" indicator change

### ISSUE THREAD

**Issue by spapando** [Brown-University-Library/usep-data#160]
Currently, we indicate a lack of word break between lines in a transcription (i.e. where `<lb break=“no” n=“1”/>`) with a “ - “ as in the end of line 2 and line 3 below. 
![image](https://user-images.githubusercontent.com/60520420/88207073-3eec1a80-cc1d-11ea-8a00-f50b52a3b9ce.png)

However, it should be indicated with “ = “, i.e. 
Iulia Helpi=
s patron=
o suo

Could someone fix this please?

**Comment by sdigiulio** [comment]
@emylonas I think this is coming out of the EpiDoc display xsl? I feel like we were planning to back over that soon anyone, so we should add this to the list of tweaks to make.

**Comment by jbodel** [comment]
Thanks, please do. In Krummrey-Panciera (and other systems) "-" indicates a
single character unable to be deciphered so can be ambivalent.

**Comment by jbodel** [comment]
Renewed request: Standard Panciera Krummrey conventions call for word break at line end to be indicted by "=", precisely in order to distinguish that lexical circumstance from the mark used to indicate a single space or illegible letter "-". So, all our word-breaks are incorrectly marked. EDR, EDH, and Gabby's ICS editions all do it correctly, so we stand out.

**Comment by sdigiulio** [comment]
Fixed in https://github.com/Brown-University-Library/usep-data/pull/203
