### ISSUE TITLE
Inscription display formatting

### ISSUE THREAD

**Issue by sdigiulio** [Brown-University-Library/usep-data#52]
Margins for metadata need expanding, other elements of individual inscription display need refining.

**Comment by emylonas** [comment]
To begin with, margins are being handled in the code issues, as the CSS that controls them is in a peculiar place, and we can't edit it: https://github.com/Brown-University-Library/usepweb_project/issues/55

**Comment by sdigiulio** [comment]
I'm assuming that this has been fixed since the linked issue at the code repo has been closed.

**Comment by jbodel** [comment]
Does this mean "unfixable"?  "the CSS that controls them is in a peculiar
place, and we can't edit it"

**Comment by emylonas** [comment]
This is not unfixable - just requires changing the coe

**Comment by emylonas** [comment]
Re-opening because the issue that has been closed was to put the css in a file that is more easily accessed, rather than inserting it directly into the template file. The CSS is in a separate file now and although it requires changes to the code directory, can be modified. 

Ideally, we will do experiment using the web page inspector to determine the width that looks best before changing in the django code.

**Comment by jbodel** [comment]
Thanks!

**Comment by emylonas** [comment]
Clsoing. This has been fixed with https://github.com/Brown-University-Library/usepweb_project/commit/0df74
