### ISSUE TITLE
Addition of Responsibility Statements

### ISSUE THREAD

**Issue by sdigiulio** [Brown-University-Library/usep-data#55]
`@resp` statements should be added where possible, in addition to more robust monitoring of file editors; will need to sort out precisely how best to implement.

**Comment by emylonas** [comment]
@sdigiulio the problem is that the output file that is created by the xsl file is in a `result-document` your template is outside that result-document. So you have to call it in the right place, just as we call the bibliography at line 323. That will at least get things to appear in the file. Then you can figure out what's going on with the actual code!

**Comment by sdigiulio** [comment]
xsl has been revised; provisionally added to the USEP website in 55316897. The display needs to be be fixed (there are spacing issues, among other things), but the Author/Editor section, along with the display of who worked on the page, is now visible on all files.

**Comment by sdigiulio** [comment]
Fixed some of the spacing in f6803990; still would like to get it to display after the transcription but before the bibl, @emylonas, but it's already looking much better.

**Comment by sdigiulio** [comment]
I think this has been addressed by #104; closing.
